[package]
name = "reloc8"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
eframe = "0.29.1"
egui = "0.29.1"
env_logger = "0.11.5"
log = "0.4.22"
serde = "1.0.215"
serde_json = "1.0.133"
sha256 = "1.5.0"
